name: 发布 Docker 镜像

on:
  release:
    types:
      - published

jobs:
  docker-publish:
    name: '构建并发布 Docker 镜像'
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v5

      - name: 设置版本
        run: |
          (git describe --tags --exact-match \
            || git symbolic-ref -q --short HEAD \
            || git rev-parse --short HEAD) > version.txt 2> /dev/null

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到 DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 登录到容器注册表
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker 元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
            xiaolfeng/wakapi-cn
          tags: |
            latest
            alpine
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: 构建并推送
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
