name: 发布版本

on:
  release:
    types:
      - published

jobs:
  release:
    name: '构建、打包并发布到 GitHub'
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
          - platform: ubuntu-latest
            GOOS: linux
            GOARCH: arm64
          - platform: windows-latest
            GOOS: windows
            GOARCH: amd64
          - platform: macos-latest
            GOOS: darwin
            GOARCH: amd64
          - platform: macos-latest
            GOOS: darwin
            GOARCH: arm64
    runs-on: ${{ matrix.platform }}

    steps:

    - name: 设置 Go 1.x
      uses: actions/setup-go@v6
      with:
        go-version: ^1.25
        cache: false
      id: go

    - name: 检出代码到 Go 模块目录
      uses: actions/checkout@v5

    - name: 设置版本
      shell: bash
      run: |
        (git describe --tags --exact-match \
          || git symbolic-ref -q --short HEAD \
          || git rev-parse --short HEAD) > version.txt 2> /dev/null

    - name: 准备
      run: |
        mkdir -p dist/ && cd dist/
        cp ../config.default.yml config.yml

    - name: 构建
      working-directory: ./dist
      shell: bash
      run: |
        GOOS=${{ matrix.GOOS }} GOARCH=${{ matrix.GOARCH }} CGO_ENABLED=0 GOEXPERIMENT=greenteagc,jsonv2 \
            go build -v -ldflags '-w -s' ../

    - name: 压缩工作文件夹（Windows PowerShell）
      working-directory: ./dist
      if: "${{ matrix.GOOS == 'windows' }}"
      run: |
        Compress-Archive -Path .\wakapi.exe, .\config.yml -DestinationPath wakapi_${{ matrix.GOOS }}_${{ matrix.GOARCH }}.zip

    - name: 压缩工作文件夹
      working-directory: ./dist
      if: "${{ matrix.GOOS != 'windows' }}"
      run: |
        zip -9 wakapi_${{ matrix.GOOS }}_${{ matrix.GOARCH }}.zip *

    - name: 上传构建的可执行文件到 Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./dist/*.zip
